on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Send start message to Telegram
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.CHAT_ID }}
          token: ${{ secrets.BOT_TOKEN }}
          message: |
            Build started for commit ${{ github.sha }}
            Commit message: ${{ github.event.head_commit.message }}

      - uses: actions/checkout@v4

      - name: set up JDK 19
        uses: actions/setup-java@v4
        with:
          java-version: '19'
          distribution: 'temurin'
          cache: gradle

      - uses: oven-sh/setup-bun@v2

      - name: Restore Gradle cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Restore Android build outputs cache
        uses: actions/cache@v3
        with:
          path: |
            android/.gradle
            android/app/build
          key: ${{ runner.os }}-android-build-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-android-build-

      - name: Install npm dependencies with bun
        run: bun install

      - name: Grant execute permission for gradlew
        run: cd android && chmod +x gradlew

      - name: Build Android Release
        run: cd android && ./gradlew assembleRelease

      - name: Rename apk files
        run: |
          cd android/app/build/outputs/apk/release/
          mv app-arm64-v8a-release.apk Tech_Triangle-nightly-arm64-v8a.apk
          mv app-armeabi-v7a-release.apk Tech_Triangle-nightly-armeabi-v7a.apk
          mv app-x86-release.apk Tech_Triangle-nightly-x86.apk
          mv app-x86_64-release.apk Tech_Triangle-nightly-x86_64.apk
          mv app-universal-release.apk Tech_Triangle-nightly-universal.apk

      - name: Send message to Telegram
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.CHAT_ID }}
          token: ${{ secrets.BOT_TOKEN }}
          message: |
            ${{github.event.head_commit.message}}

      - name: Send APKs to Telegram
        run: |
          for file in android/app/build/outputs/apk/release/Tech_Triangle-nightly-*.apk; do
            curl -s -X POST https://api.telegram.org/bot${{ secrets.BOT_TOKEN }}/sendDocument \
              -F chat_id=${{ secrets.CHAT_ID }} \
              -F document=@"$file"
          done

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: tech-triangle-arm64-v8a
          path: android/app/build/outputs/apk/release/Tech_Triangle-nightly-arm64-v8a.apk

      - uses: actions/upload-artifact@v4
        with:
          name: tech-triangle-armeabi-v7a
          path: android/app/build/outputs/apk/release/Tech_Triangle-nightly-armeabi-v7a.apk

      - uses: actions/upload-artifact@v4
        with:
          name: tech-triangle-x86
          path: android/app/build/outputs/apk/release/Tech_Triangle-nightly-x86.apk

      - uses: actions/upload-artifact@v4
        with:
          name: tech-triangle-x86_64
          path: android/app/build/outputs/apk/release/Tech_Triangle-nightly-x86_64.apk

      - uses: actions/upload-artifact@v4
        with:
          name: tech-triangle-universal
          path: android/app/build/outputs/apk/release/Tech_Triangle-nightly-universal.apk

      - name: Update Nightly Release
        uses: andelf/nightly-release@main
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          tag_name: nightly
          name: 'Tech Triangle Nightly Release $$'
          prerelease: false
          body: |
            ${{github.event.head_commit.message}}
          files: |
            android/app/build/outputs/apk/release/Tech_Triangle-nightly-arm64-v8a.apk
            android/app/build/outputs/apk/release/Tech_Triangle-nightly-armeabi-v7a.apk
            android/app/build/outputs/apk/release/Tech_Triangle-nightly-x86.apk
            android/app/build/outputs/apk/release/Tech_Triangle-nightly-x86_64.apk
            android/app/build/outputs/apk/release/Tech_Triangle-nightly-universal.apk
