name: Build Android Release

on:
  # workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: set up JDK 19
        uses: actions/setup-java@v4
        with:
          java-version: '19'
          distribution: 'temurin'
          cache: gradle

      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v2

      - name: Install npm dependencies with bun
        run: |
          bun install

      - name: Grant execute permission for gradlew
        run: cd android && chmod +x gradlew

      - name: Build Android Release
        run: |
          cd android && ./gradlew assembleRelease

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: computer-science.apk
          path: android/app/build/outputs/apk/release/Tech_Triangle-arm64-v8a.apk