on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: set up JDK 19
        uses: actions/setup-java@v4
        with:
          java-version: '19'
          distribution: 'temurin'
          cache: gradle

      - uses: oven-sh/setup-bun@v2

      - name: Restore Gradle cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Restore Android build outputs cache
        uses: actions/cache@v3
        with:
          path: |
            android/.gradle
            android/app/build
          key: ${{ runner.os }}-android-build-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-android-build-

      - name: Install npm dependencies with bun
        run: bun install

      - name: Grant execute permission for gradlew
        run: cd android && chmod +x gradlew

      - name: Build Android Release
        run: cd android && ./gradlew assembleRelease

      - name: send telegram message on push
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          document: "./android/app/build/outputs/apk/release/Tech_Triangle-arm64-v8a.apk"
          message: |
            ${{ github.actor }} created commit:
            Commit message: ${{ github.event.commits[0].message }}

            Repository: ${{ github.repository }}

            See changes: https://github.com/${{ github.repository }}/commit/${{github.sha}}

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: tech-triangle
          path: android/app/build/outputs/apk/release/Tech_Triangle-arm64-v8a.apk
